//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        public int car_id { get; set; }
        public Nullable<int> car_brand { get; set; }
        public string car_model { get; set; }
        public Nullable<int> car_baseprice { get; set; }
    
        public virtual brands brands { get; set; }
    }
}
