//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mocking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avenger
    {
        public string Name { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> Superpower { get; set; }
        public Nullable<decimal> Strength { get; set; }
    }
}
